# ============================================================
# UI Sequence Call -- Register Scheduled Task
# Creates a Windows Task Scheduler task that:
#   - Auto-starts at system boot
#   - Runs as SYSTEM (configurable)
#   - Auto-restarts on crash (every 1 minute, up to 999 times)
#   - Has no execution time limit
#   - Captures stdout / stderr to log files in the install dir
# ============================================================
#
# Requires elevation (admin) -- registering a SYSTEM-account task
# is a privileged operation.
#
# Prerequisite: extract the release zip to your install location and edit
# UISequenceCall.properties with real DB credentials. Then run this script
# pointing at that location:
#
#   .\register_task.ps1 -InstallDir <path> [-TaskName UISequenceCall]
#                      [-JavaPath <path>] [-RunAsUser SYSTEM]
#                      [-StartImmediately]
# ============================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$InstallDir,

    [string]$TaskName = "UISequenceCall",
    [string]$JavaPath = "",
    [string]$RunAsUser = "SYSTEM",
    [switch]$StartImmediately
)

$ErrorActionPreference = "Stop"

# ============================================================
# Validation
# ============================================================
function Assert-Admin {
    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Error "register_task.ps1 must be run from an elevated PowerShell (Run as Administrator)."
        exit 1
    }
}
Assert-Admin

$InstallDir = $InstallDir.Trim().TrimEnd('\')
if (-not (Test-Path $InstallDir)) {
    Write-Error "Install directory not found: $InstallDir"
    exit 1
}
$jarPath = Join-Path $InstallDir "ui-sequence-call-1.0.0-jar-with-dependencies.jar"
if (-not (Test-Path $jarPath)) {
    Write-Error "Jar not found at: $jarPath -- run install.ps1 first."
    exit 1
}

# ============================================================
# Resolve java.exe
# ============================================================
if (-not $JavaPath) {
    $javaCmd = Get-Command java.exe -ErrorAction SilentlyContinue
    if ($javaCmd) {
        $JavaPath = $javaCmd.Source
    } elseif ($env:JAVA_HOME -and (Test-Path "$env:JAVA_HOME\bin\java.exe")) {
        $JavaPath = "$env:JAVA_HOME\bin\java.exe"
    } else {
        Write-Error "Could not locate java.exe. Pass -JavaPath explicitly or ensure 'java' is on PATH / `$env:JAVA_HOME is set."
        exit 1
    }
}
if (-not (Test-Path $JavaPath)) {
    Write-Error "java.exe not found at: $JavaPath"
    exit 1
}
Write-Host "  Java: $JavaPath" -ForegroundColor Cyan
Write-Host "  Install dir: $InstallDir" -ForegroundColor Cyan
Write-Host "  Task name: $TaskName" -ForegroundColor Cyan
Write-Host "  Run as: $RunAsUser" -ForegroundColor Cyan

# ============================================================
# Generate a wrapper batch file in the install dir.
# Why: the Scheduled Task runs ONE command and Windows doesn't
# natively redirect stdout/stderr. A small wrapper handles the
# redirect cleanly, no quoting acrobatics in the task action.
# ============================================================
$serviceCmd = Join-Path $InstallDir "service_run.cmd"
$serviceCmdContent = @"
@echo off
REM Auto-generated by register_task.ps1 -- do not edit; re-run the installer to regenerate.
cd /d "%~dp0"
"$JavaPath" -jar ui-sequence-call-1.0.0-jar-with-dependencies.jar 1>> service_stdout.log 2>> service_stderr.log
"@
Set-Content -Path $serviceCmd -Value $serviceCmdContent -Encoding ASCII
Write-Host "  Wrote $serviceCmd" -ForegroundColor Green

# ============================================================
# Remove existing task with same name, if any (idempotent).
# ============================================================
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Write-Host "  Existing task '$TaskName' found -- removing first..." -ForegroundColor Yellow
    Stop-ScheduledTask    -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

# ============================================================
# Build the task definition
# ============================================================
$action = New-ScheduledTaskAction `
    -Execute $serviceCmd `
    -WorkingDirectory $InstallDir

$trigger = New-ScheduledTaskTrigger -AtStartup

$principal = New-ScheduledTaskPrincipal `
    -UserId $RunAsUser `
    -LogonType ServiceAccount `
    -RunLevel Highest

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 999 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero)

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Principal $principal `
    -Settings $settings | Out-Null

Write-Host ""
Write-Host "=== Task '$TaskName' registered ===" -ForegroundColor Green
Write-Host "  Auto-starts at boot, restarts on crash, no time limit"
Write-Host "  Logs: $InstallDir\service_stdout.log, service_stderr.log"
Write-Host "         $InstallDir\UISequenceCall.log (java.util.logging output)"

if ($StartImmediately) {
    Write-Host ""
    Write-Host "Starting task..." -ForegroundColor Cyan
    Start-ScheduledTask -TaskName $TaskName
    Start-Sleep -Seconds 2
    $info = Get-ScheduledTaskInfo -TaskName $TaskName
    Write-Host "  Last run: $($info.LastRunTime)"
    Write-Host "  Last result code: $($info.LastTaskResult) (0 = OK / running)"
    Write-Host ""
    Write-Host "Verify via browser: http://localhost:8080/sequence"
} else {
    Write-Host ""
    Write-Host "Task registered but not started. To start now:"
    Write-Host "    Start-ScheduledTask -TaskName $TaskName"
    Write-Host "Or reboot -- it will auto-start."
}

Write-Host ""
Write-Host "Lifecycle commands:"
Write-Host "    Get-ScheduledTask        -TaskName $TaskName    # check status"
Write-Host "    Get-ScheduledTaskInfo    -TaskName $TaskName    # last run info"
Write-Host "    Stop-ScheduledTask       -TaskName $TaskName"
Write-Host "    Start-ScheduledTask      -TaskName $TaskName"
Write-Host "    .\unregister_task.ps1    -TaskName $TaskName    # remove cleanly"
